//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ResourceExceptionsMessages", typeof(ResourceExceptionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
<<<<<<< HEAD
    }
}
=======

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EMPTY => ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EXISTS => ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_OR_PASSWORD_INVALID => ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_EMAIL => ResourceManager.GetString("INVALID_EMAIL", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NAME_EMPTY => ResourceManager.GetString("NAME_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_EMPTY => ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string SHORT_PASSWORD => ResourceManager.GetString("SHORT_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string UKNOW_ERROR => ResourceManager.GetString("UKNOW_ERROR", resourceCulture);

	}
}
>>>>>>> f8ae38e (test: integrations tests for register user was added)
