//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ResourceExceptionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ResourceExceptionsMessages", typeof(ResourceExceptionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EMPTY => ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EXISTS => ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_OR_PASSWORD_INVALID => ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_EMAIL => ResourceManager.GetString("INVALID_EMAIL", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NAME_EMPTY => ResourceManager.GetString("NAME_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NO_TOKEN => ResourceManager.GetString("NO_TOKEN", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_EMPTY => ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string SHORT_PASSWORD => ResourceManager.GetString("SHORT_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string TOKEN_INVALID => ResourceManager.GetString("TOKEN_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string TOKEN_WITHOUT_PERMISSION => ResourceManager.GetString("TOKEN_WITHOUT_PERMISSION", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string UKNOW_ERROR => ResourceManager.GetString("UKNOW_ERROR", resourceCulture);

	}
}